### ISSUE TITLE
Transitions between Tracks not working

### ISSUE THREAD

**Issue by PhilippvK** [PhilippvK/playforia-minigolf#2] opened 2020-03-18 22:27 UTC
When finishing or skipping a Minigolf track in Singleplayer oder Multiplayer, the next track kn the round should start automatically. This feature is not working as expected.

**Comment by Helsionium** [comment] 2020-03-25 08:39
This issue is caused by a NullPointerException on the server and can be fixed by replacing

track.getFirstBestPlayer().equals("")

with

"".equals(track.getFirstBestPlayer())

in line 207 of the class org.moparforia.server.game.gametypes.GolfGame

**Comment by PhilippvK** [comment] 2020-03-25 10:11
@Helsionium Thank you for figuring this out. This was probably related to the Highscore functionality, which is nicht working anymore.

Should I fix this line by myself or can I expect a Pull Request?

**Comment by Helsionium** [comment] 2020-03-25 10:26
@PhilippvK Please fix it yourself, I don't have any experience with GitHub and don't really know how this works. Thank you!

**Closed** 2020-03-25 10:47 UTC
